### ISSUE TITLE
Incorrect and mismatched total fuel capacites on tweakscaled E wings

### ISSUE THREAD

**Issue by 321nick** [net-lisias-ksp/TweakScaleCompanion_OPT#4]
As the title says, im running twekscale Lisias branch, and tweakscale companion for OPT. when i set the wings from structural too fuel, the mirrored wing has way more fuel than the other, and it starts not fully filled. 

https://gist.github.com/12728f6cb7ed76704c00dc7d90f58357

https://gist.github.com/4d117d91f7f8399e11c4f62118db6b86

**Comment by 321nick** [comment]
ok, so idk what happened i loaded the plane again in the SPH and added kerosene too the wings it worked just fine...so, sorry for the false report.

**Comment by Lisias** [comment]
Just for (moar) information, it is possible this can be related to B9PartSwitch's Life Cycle (I had a mishap like that once with B9PS).

There's no predefined order in which the Modules are called, so TweakScales tries its best to force being the last one being called on the party, but now and then this borks and someone ended up being called **after** TweakScale and screw up something TweakScale had done.

Since reloading the craft "fixed" the issue, I think this may be the cause of your initial glitch.

If this happens again, check if it happens on every part or only on some. This can help to trim down the possibilities.

(one good side effect of kSP 1.12 being the last release is that I finally will have time to play KSP and do exploratory tests again, as there will be no more breakage to diagnose and workaround...)

**Comment by Lisias** [comment]
(It also worths to mention that B9PS appears to do not handle OnCopy, and this is needed when building symmetries)
